[package]
name = "ffs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
eyre = "0.6.12"
ignore = "0.4.22"
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.19"
