[package]
name = "ffs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
dashmap = "6.0.1"
eyre = "0.6.12"
ignore = "0.4.22"
starlark = "0.12.0"
thiserror = "1.0.63"
