[package]
name = "ffs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
context_attr = { version = "0.1.1", features = ["eyre"] }
dashmap = "6.0.1"
eyre = "0.6.12"
ignore = "0.4.22"
starlark = "0.12.0"
thiserror = "1.0.63"
